language: r
sudo: false
install:
  - make

script:
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'

before_install:
  - echo $key_secret_password | gpg --passphrase-fd 0 deploy_key.gpg
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"

env:
  global:
    secure: "dpuMepYc7K3H2X1fq0KQS+SYJT0EAWrMqHvC8PLwjF/GnRu1Bf9FZ9yNtaIib164tZohi6iHRfzQZCYbId3PDYiwjErlCgXkCThu0iNumVUkfuiBV5iKW9LqP1cqvZjX8JuHWC66G2h+KnRCgYtPwKqB2GOxv5EAy/8+XPREggPzb7kvKJowbxHIvcGYdYDZ/k0ww/G4qb6JJhkXAjWPElrXja8917QODXaP7gc+ZqX7rfrGyHpU1XRSIj2C4eWCJ9MbiLalujowpa7Ynemxe639hPGK9177PMM9ARcrJRrsoBITlCtW3JFEeFDj0ZLXdhcWns2hIxcTgXoX6sI8AZI7FcbEK67q1jkLkc+/gMrAq5Lb7UDtIT5Rqw8P/JF4+nQC+KFI9kuO7chQgzf8ZSsThEyACcZZe9I5CqYlj/D3b+9BNmWyPrUhKy4V4NynxqRGytogpcwyONmqgefXx/w8md5EmXtQhos4dyWfUFG5K91HbXDipS9Pzd+GMhBPxl0J518AyED9r+OXvlSm8dkXRYyy8qGKQKw30n4bsORwteo0oq5AR2dUhNsK4eejppK5oeYsJhHs6OhwlWtUsTxK364xloGTOWs6HJUSQ1/5/7bIWJ1OaiecpGbu3jLc7E+z1F9ZWZx5THUIs8Qe9nGqogweG0mccSkLzynZKoY="
